alter table if exists chat_user_access_roles add constraint fk_chat_user_access_role_chat_id foreign key (chat_id) references chats;
alter table if exists chat_user_access_roles add constraint fk_chat_user_access_role_chat_access_role_id foreign key (chat_access_role_id) references chat_access_roles;
alter table if exists chat_user_access_roles add constraint fk_chat_user_access_role_user_id foreign key (user_id) references users;
alter table if exists chats add constraint fk_chat_music_band_id foreign key (music_band_id) references music_bands;
alter table if exists event_songs add constraint fk_event_song_event_id foreign key (event_id) references events;
alter table if exists event_songs add constraint fk_event_song_song_id FOREIGN KEY (song_id) REFERENCES songs (id) ON DELETE SET NULL;
alter table if exists event_users add constraint fk_event_user_event_id foreign key (event_id) references events;
alter table if exists event_users add constraint fk_event_user_participation_status_id foreign key (participation_status_id) references participation_statuses;
alter table if exists event_users add constraint fk_event_user_stage_role_id foreign key (stage_role_id) references stage_roles;
alter table if exists event_users add constraint fk_event_user_user_id FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE SET NULL;
alter table if exists events add constraint fk_event_event_category_id foreign key (event_category_id) references event_categories;
alter table if exists events add constraint fk_event_music_band_id foreign key (music_band_id) references music_bands;
alter table if exists invitations add constraint fk_invitation_music_band_id foreign key (music_band_id) references music_bands;
alter table if exists invitations add constraint fk_invitation_participation_status_id foreign key (participation_status_id) references participation_statuses;
alter table if exists messages add constraint fk_message_chat_id foreign key (chat_id) references chats;
alter table if exists messages add constraint fk_message_user_id FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE SET NULL;
alter table if exists music_band_user_access_roles add constraint fk_music_band_user_access_role_music_band_id foreign key (music_band_id) references music_bands;
alter table if exists music_band_user_access_roles add constraint fk_music_band_user_access_role_music_band_access_role_id foreign key (music_band_access_role_id) references music_band_access_roles;
alter table if exists music_band_user_access_roles add constraint fk_music_band_user_access_role_user_id foreign key (user_id) references users;
alter table if exists music_band_user_stage_roles add constraint fk_music_band_user_stage_role_music_band_id foreign key (music_band_id) references music_bands;
alter table if exists music_band_user_stage_roles add constraint fk_music_band_user_stage_role_stage_role_id foreign key (stage_role_id) references stage_roles;
alter table if exists music_band_user_stage_roles add constraint fk_music_band_user_stage_role_user_id foreign key (user_id) references users;
alter table if exists songs add constraint fk_song_music_band_id foreign key (music_band_id) references music_bands;
alter table if exists user_roles add constraint fk_user_role_role_id foreign key (role_id) references roles;
alter table if exists user_roles add constraint fk_user_role_user_id foreign key (user_id) references users;
